'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { AlertCircle, CheckCircle, Loader2 } from 'lucide-react';
import { api } from '@/lib/api';
import { FAKER_RULES, inferFakerRule } from '@/lib/faker-mapping';

interface Column {
  name: string;
  type: string;
  nullable?: boolean;
  primaryKey?: boolean;
  defaultValue?: string | null;
}

interface DataGeneratorDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  schemaName: string;
  tableName: string;
  columns: Column[];
  onSuccess?: () => void;
}

interface ColumnRule {
  columnName: string;
  columnType: string;
  fakerRule: string;
  skip: boolean;
}

type GeneratorStatus = 'config' | 'preview' | 'generating' | 'done' | 'error';

export function DataGeneratorDialog({
  open,
  onOpenChange,
  schemaName,
  tableName,
  columns,
  onSuccess,
}: DataGeneratorDialogProps) {
  const [status, setStatus] = useState<GeneratorStatus>('config');
  const [count, setCount] = useState(10);
  const [rules, setRules] = useState<ColumnRule[]>([]);
  const [previewData, setPreviewData] = useState<Record<string, unknown>[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [insertedCount, setInsertedCount] = useState(0);

  // Initialize rules when columns change
  useEffect(() => {
    if (columns.length > 0) {
      const initialRules = columns.map((col) => {
        // Skip auto-generated columns (serial, uuid with default, etc.)
        const isAutoGenerated = Boolean(
          col.primaryKey ||
          col.type.toLowerCase().includes('serial') ||
          (col.defaultValue && col.defaultValue.includes('uuid_generate'))
        );

        return {
          columnName: col.name,
          columnType: col.type,
          fakerRule: inferFakerRule(col.name, col.type),
          skip: isAutoGenerated,
        };
      });
      setRules(initialRules);
    }
  }, [columns]);

  const reset = useCallback(() => {
    setStatus('config');
    setCount(10);
    setPreviewData([]);
    setError(null);
    setInsertedCount(0);
  }, []);

  const handleOpenChange = (newOpen: boolean) => {
    if (!newOpen) reset();
    onOpenChange(newOpen);
  };

  const updateRule = (columnName: string, fakerRule: string) => {
    setRules((prev) =>
      prev.map((r) => (r.columnName === columnName ? { ...r, fakerRule } : r))
    );
  };

  const toggleSkip = (columnName: string) => {
    setRules((prev) =>
      prev.map((r) => (r.columnName === columnName ? { ...r, skip: !r.skip } : r))
    );
  };

  const generatePreview = async () => {
    setError(null);
    setStatus('preview');

    try {
      // Dynamic import faker to reduce bundle size
      const { faker } = await import('@faker-js/faker');

      const data: Record<string, unknown>[] = [];
      for (let i = 0; i < Math.min(count, 10); i++) {
        const row: Record<string, unknown> = {};
        for (const rule of rules) {
          if (rule.skip) continue;
          const fakerRule = FAKER_RULES[rule.fakerRule];
          if (fakerRule) {
            row[rule.columnName] = fakerRule.generate(faker);
          }
        }
        data.push(row);
      }
      setPreviewData(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : '生成预览失败');
      setStatus('error');
    }
  };

  const handleGenerate = async () => {
    setStatus('generating');
    setError(null);

    try {
      const { faker } = await import('@faker-js/faker');

      // Generate all rows
      const rows: Record<string, unknown>[] = [];
      for (let i = 0; i < count; i++) {
        const row: Record<string, unknown> = {};
        for (const rule of rules) {
          if (rule.skip) continue;
          const fakerRule = FAKER_RULES[rule.fakerRule];
          if (fakerRule) {
            row[rule.columnName] = fakerRule.generate(faker);
          }
        }
        rows.push(row);
      }

      // Batch insert using existing import API
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001'}/api/v1/schemas/${schemaName}/tables/${tableName}/import`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${api.getToken()}`,
          },
          body: JSON.stringify({ rows, options: { onError: 'skip', batchSize: 100 } }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        throw new Error(errorData.error?.message || `插入失败 (${response.status})`);
      }

      const result = await response.json();
      setInsertedCount(result.imported || rows.length);
      setStatus('done');
      onSuccess?.();
    } catch (err) {
      setError(err instanceof Error ? err.message : '生成数据失败');
      setStatus('error');
    }
  };

  const fakerRuleOptions = Object.entries(FAKER_RULES).map(([key, rule]) => ({
    value: key,
    label: rule.label,
  }));

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>生成测试数据 - {tableName}</DialogTitle>
        </DialogHeader>

        {status === 'config' && (
          <div className="space-y-6">
            <div>
              <Label htmlFor="count">生成数量</Label>
              <Input
                id="count"
                type="number"
                min={1}
                max={100}
                value={count}
                onChange={(e) => setCount(Math.min(100, Math.max(1, parseInt(e.target.value) || 1)))}
                className="w-32 mt-1"
              />
              <p className="text-sm text-muted-foreground mt-1">最多 100 条</p>
            </div>

            <div>
              <Label className="mb-2 block">字段生成规则</Label>
              <div className="border rounded-lg divide-y">
                {rules.map((rule) => (
                  <div key={rule.columnName} className="flex items-center gap-4 p-3">
                    <div className="flex-1">
                      <div className="font-medium">{rule.columnName}</div>
                      <div className="text-sm text-muted-foreground">{rule.columnType}</div>
                    </div>
                    <div className="flex items-center gap-2">
                      <Select
                        value={rule.skip ? '__skip__' : rule.fakerRule}
                        onValueChange={(value) => {
                          if (value === '__skip__') {
                            toggleSkip(rule.columnName);
                          } else {
                            if (rule.skip) toggleSkip(rule.columnName);
                            updateRule(rule.columnName, value);
                          }
                        }}
                      >
                        <SelectTrigger className="w-40">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="__skip__">跳过（自动生成）</SelectItem>
                          {fakerRuleOptions.map((opt) => (
                            <SelectItem key={opt.value} value={opt.value}>
                              {opt.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {status === 'preview' && (
          <div className="space-y-4">
            <div>
              <h3 className="font-medium mb-2">预览数据（前 {previewData.length} 条）</h3>
              <div className="border rounded overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-muted">
                    <tr>
                      {rules
                        .filter((r) => !r.skip)
                        .map((rule) => (
                          <th key={rule.columnName} className="px-3 py-2 text-left font-medium">
                            {rule.columnName}
                          </th>
                        ))}
                    </tr>
                  </thead>
                  <tbody>
                    {previewData.map((row, idx) => (
                      <tr key={idx} className="border-t">
                        {rules
                          .filter((r) => !r.skip)
                          .map((rule) => (
                            <td key={rule.columnName} className="px-3 py-2 max-w-xs truncate">
                              {String(row[rule.columnName] ?? '')}
                            </td>
                          ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
            <p className="text-sm text-muted-foreground">
              确认后将生成 {count} 条数据并插入表中
            </p>
          </div>
        )}

        {status === 'generating' && (
          <div className="flex items-center justify-center py-8">
            <div className="text-center">
              <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-primary" />
              <p>正在生成并插入数据...</p>
            </div>
          </div>
        )}

        {status === 'done' && (
          <div className="space-y-4 py-4">
            <div className="flex items-center gap-2 text-green-600">
              <CheckCircle className="h-5 w-5" />
              <span className="font-medium">生成完成</span>
            </div>
            <p>成功插入 {insertedCount} 条测试数据</p>
          </div>
        )}

        {status === 'error' && (
          <div className="flex items-center gap-2 text-red-600 py-4">
            <AlertCircle className="h-5 w-5" />
            <span>{error}</span>
          </div>
        )}

        <DialogFooter>
          {status === 'config' && (
            <Button onClick={generatePreview}>预览数据</Button>
          )}
          {status === 'preview' && (
            <>
              <Button variant="outline" onClick={() => setStatus('config')}>
                返回配置
              </Button>
              <Button onClick={handleGenerate}>确认生成</Button>
            </>
          )}
          {(status === 'done' || status === 'error') && (
            <>
              {status === 'error' && (
                <Button variant="outline" onClick={() => setStatus('config')}>
                  重试
                </Button>
              )}
              <Button onClick={() => handleOpenChange(false)}>关闭</Button>
            </>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
