import { randomUUID } from 'node:crypto'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { config } from '../../apps/api/src/config/index.js'
import { pool } from '../../apps/api/src/db/index.js'
import { DataAccessValidationError } from '../../apps/api/src/modules/data-access/data-access-policy.js'
import {
  getProjectDataAccessOverview,
  getTableDataAccess,
  updateTableDataAccess,
} from '../../apps/api/src/modules/data-access/data-access.service.js'
import { resolveDataScopeRole } from '../../apps/api/src/modules/data-access/data-scope-role.js'
import { hasuraMetadataRequest } from '../../apps/api/src/modules/realtime/realtime.service.js'
import * as projectService from '../../apps/api/src/modules/project/project.service.js'
import * as tenantService from '../../apps/api/src/modules/tenant/tenant.service.js'

const runIntegration = process.env.DRUVIA_RUN_DATA_ACCESS_COLUMN_INTEGRATION === '1'
const TABLE_NAME = 'generated_observations'

describe.skipIf(!runIntegration)('data access generated columns against PostgreSQL and Hasura', () => {
  let userUid = 0
  let userId = ''
  let tenantId = ''
  let projectId = ''
  let schemaName = ''
  let originalAdminSecret = ''

  beforeAll(async () => {
    const integrationAdminSecret = process.env.DRUVIA_INTEGRATION_HASURA_ADMIN_SECRET || ''
    if (!integrationAdminSecret) throw new Error('Integration test requires a Hasura admin secret')
    originalAdminSecret = config.hasura.adminSecret
    config.hasura.adminSecret = integrationAdminSecret

    const suffix = randomUUID().replaceAll('-', '').slice(0, 8)
    userId = `columns-${suffix}`
    const user = await pool.query<{ id: number }>(
      `INSERT INTO druvia_users (user_id, email, username, status)
       VALUES ($1, $2, $3, 'active') RETURNING id`,
      [userId, `${userId}@test.local`, `columns_${suffix}`]
    )
    userUid = user.rows[0].id
    const tenant = await tenantService.createTenant({
      alias: `c${suffix}`.slice(0, 16),
      name: 'Data Access Column Integration',
      ownerUid: userUid,
    })
    tenantId = tenant.tenantId
    const project = await projectService.createProject({
      tenantId,
      alias: `g${suffix}`.slice(0, 16),
      name: 'Generated Column Integration',
    })
    projectId = project.projectId
    schemaName = project.schemaName || ''
    if (!schemaName) throw new Error('Fixture project schema was not created')

    await pool.query(`
      CREATE TABLE "${schemaName}"."${TABLE_NAME}" (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        system_id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
        owner_id TEXT NOT NULL,
        message TEXT NOT NULL,
        message_upper TEXT GENERATED ALWAYS AS (upper(message)) STORED
      )
    `)
  }, 30_000)

  afterAll(async () => {
    if (schemaName) {
      await hasuraMetadataRequest('pg_untrack_table', {
        source: 'default',
        table: { schema: schemaName, name: TABLE_NAME },
        cascade: true,
      }).catch(() => undefined)
      await pool.query(`DROP SCHEMA IF EXISTS "${schemaName}" CASCADE`).catch(() => undefined)
    }
    if (projectId) {
      await pool.query('DELETE FROM druvia_projects WHERE project_id = $1', [projectId]).catch(() => undefined)
    }
    if (tenantId) {
      await pool.query('DELETE FROM druvia_tenants WHERE tenant_id = $1', [tenantId]).catch(() => undefined)
    }
    if (userUid) {
      await pool.query('DELETE FROM druvia_users WHERE id = $1', [userUid]).catch(() => undefined)
    }
    config.hasura.adminSecret = originalAdminSecret
  })

  it('applies and re-inspects operation-specific permissions', async () => {
    await expect(updateTableDataAccess(projectId, TABLE_NAME, {
      authenticated: {
        select: 'owner',
        insert: 'owner',
        update: 'none',
        delete: 'none',
        ownerColumn: 'message_upper',
      },
      anonymous: { select: false },
    })).rejects.toBeInstanceOf(DataAccessValidationError)

    const state = await updateTableDataAccess(projectId, TABLE_NAME, {
      authenticated: {
        select: 'owner',
        insert: 'owner',
        update: 'all',
        delete: 'none',
        ownerColumn: 'owner_id',
      },
      anonymous: { select: true },
    })

    expect(state.columns).toEqual(['id', 'system_id', 'owner_id', 'message', 'message_upper'])
    expect((await getTableDataAccess(projectId, TABLE_NAME)).managedState).toBe('managed')
    const overview = await getProjectDataAccessOverview(projectId)
    expect(overview.tables.find((table) => table.tableName === TABLE_NAME)).toMatchObject({
      authenticatedAccess: 'read_write',
      anonymousAccess: 'read',
      reviewRequired: false,
    })

    const metadata = await hasuraMetadataRequest<{ sources?: Array<{
      name?: string
      tables?: Array<Record<string, unknown>>
    }> }>('export_metadata', {})
    const table = metadata.sources?.find((source) => source.name === 'default')?.tables
      ?.find((item) => {
        const identity = item.table
        return !!identity
          && typeof identity === 'object'
          && !Array.isArray(identity)
          && (identity as Record<string, unknown>).schema === schemaName
          && (identity as Record<string, unknown>).name === TABLE_NAME
      })
    const role = resolveDataScopeRole({ projectId, actor: 'authenticated' })
    const insertPermission = permissionFor(table, 'insert_permissions', role)
    const updatePermission = permissionFor(table, 'update_permissions', role)

    expect(insertPermission).toMatchObject({
      columns: ['id', 'message'],
      set: { owner_id: 'X-Hasura-User-Id' },
    })
    expect(updatePermission.columns).toEqual(['id', 'owner_id', 'message'])
    expect(JSON.stringify([insertPermission, updatePermission])).not.toContain('system_id')
    expect(JSON.stringify([insertPermission, updatePermission])).not.toContain('message_upper')
  }, 30_000)
})

function permissionFor(
  table: Record<string, unknown> | undefined,
  key: string,
  role: string
): Record<string, unknown> {
  const entries = Array.isArray(table?.[key]) ? table[key] as Array<Record<string, unknown>> : []
  const entry = entries.find((item) => item.role === role)
  if (!entry || !entry.permission || typeof entry.permission !== 'object') {
    throw new Error(`Missing ${key} for integration fixture`)
  }
  return entry.permission as Record<string, unknown>
}
